version: 2

parameters:
  workflow_to_execute:
    type: string
    default: "default"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          when: << pipeline.parameters.workflow_to_execute == 'default' >>
      - deploy:
          when: << pipeline.parameters.workflow_to_execute == 'deploy' >>

jobs:
  build:
    docker:
      - image: your-docker-image
    steps:
      - run:
          name: Build
          command: echo "Building..."

  deploy:
    docker:
      - image: your-docker-image
    steps:
      - run:
          name: Deploy
          command: echo "Deploying..."
