#changes for the master branch on 12/21/2023 only echo statements
java-docker-defaults: &java-docker-defaults
  docker:
    - image: mafs/java-builder:11-jdk
      auth:
        username: $DOCKERHUB_USER 
        password: $DOCKERHUB_PASSWORD

curl-docker-defaults: &curl-docker-defaults
  docker:
    - image: mafs/curl:latest
      auth:
        username: $DOCKERHUB_USER
        password: $DOCKERHUB_PASSWORD

maven-env-defaults: &maven-env-defaults
  <<: *java-docker-defaults
  working_directory: ~/repo
  environment:
    MAVEN_OPTS: -Xmx3200m -Dmaven.wagon.http.retryHandler.count=3
    TZ: "America/New_York"  

curl-env-defaults: &curl-env-defaults
  <<: *curl-docker-defaults
  working_directory: ~/repo

version: 2.1
parameters:
  workflow_to_execute:
    type: string
    default: "default"
   
  
jobs:
  build:
    <<: *maven-env-defaults
    steps:
      - checkout
      - run: echo "This was triggered by build << pipeline.trigger_source >>"
      - run: echo "This was triggered by build << pipeline.git.branch >>"
      - run: echo "This was triggered by branch ${{CIRCLE_BRANCH}} "
      - run:
           name: Check Git version
           command: git --version
      - run:
          name: Set Discord Details
          command: git log -1 --oneline --format="%s"

  code-analysis:
    <<: *maven-env-defaults
    steps:
      - checkout
      - run: echo "This was triggered by code-analysis << pipeline.trigger_source >>" 
  test:
    parallelism: 4
    <<: *maven-env-defaults
    steps:
      - checkout
      - run: echo "This was triggered by test << pipeline.trigger_source >>"
  publish:
    <<: *maven-env-defaults
    steps:
      - checkout
      - run: echo "This was triggered by publish << pipeline.trigger_source >>"                                          
  deploy-dev:
    <<: *curl-env-defaults
    steps:
    - checkout
    - run: echo "This was triggered by deploy-dev << pipeline.trigger_source >>"    
  deploy-qa:
    <<: *curl-env-defaults
    steps:
    - checkout
    - run: echo "This was triggered by deploy-qa<< pipeline.trigger_source >>"
  deploy-stage:
    <<: *curl-env-defaults
    steps:
    - checkout
    - run: echo "This was triggered by deploy-stage<< pipeline.trigger_source >>"
  deploy-prod:
    <<: *curl-env-defaults
    steps:
    - checkout
    - run: echo "This was triggered by << pipeline.trigger_source >>"
  tag-release:
    <<: *maven-env-defaults
    steps:
    - checkout
    - run: echo "This was triggered by << pipeline.trigger_source >>"
workflows:
  version: 2.1
  build_and_deploy:
    when: 
      and:
        - equal: [ default, <<pipeline.parameters.workflow_to_execute>> ]
    jobs:
    - build:
        context: org-global
    - code-analysis:
        context: org-global        
    - test:
        context: org-global
    - publish:
        context: org-global    
        requires:
        - build
        - code-analysis
        - test        
    - deploy-dev:
        context: org-global
        requires:
        - publish
    - hold-deploy-qa:
        type: approval
        requires:
        - deploy-dev           
    - deploy-qa:
        context: org-global
        requires:
        - hold-deploy-qa        
    - hold-deploy-stage:
        type: approval
        requires:
        - deploy-qa
    - deploy-stage:
        context: org-global      
        requires:
        - hold-deploy-stage
    - hold-deploy-prod:
        type: approval
        requires:
        - deploy-stage
        filters:
          branches:
            only: main
    - deploy-prod:
        context: org-global      
        requires:
        - hold-deploy-prod
    - tag-release:
        context: org-global      
        requires:
        - deploy-prod
  deploy_and_run:
    when: 
      and:
        - equal: [ skiptest, <<pipeline.parameters.workflow_to_execute>> ]
    jobs:
    - deploy-dev:
        context: org-global
    - hold-deploy-qa:
        type: approval
        requires:
        - deploy-dev           
    - deploy-qa:
        context: org-global
        requires:
        - hold-deploy-qa        
    - hold-deploy-stage:
        type: approval
        requires:
        - deploy-qa
    - deploy-stage:
        context: org-global      
        requires:
        - hold-deploy-stage
    - hold-deploy-prod:
        type: approval
        requires:
        - deploy-stage
    - deploy-prod:
        context: org-global      
        requires:
        - hold-deploy-prod
    - tag-release:
        context: org-global      
        requires:
        - deploy-prod	
  dev_deploy:
    when: 
      and:
        - equal: [ dev_deploy , <<pipeline.parameters.workflow_to_execute>> ]
    jobs:
    - build:
        context: org-global
    - code-analysis:
        context: org-global        
    - test:
        context: org-global
    - publish:
        context: org-global    
        requires:
        - build
        - code-analysis
        - test  
    - hold-deploy-dev:
        type: approval
        requires:
        - publish          
    - deploy-dev:
        context: org-global
        requires:
        - hold-deploy-dev
  qa_deploy:
    when: 
      and:
        - equal: [ qa_deploy , <<pipeline.parameters.workflow_to_execute>> ]
    jobs:
    - build:
        context: org-global
    - code-analysis:
        context: org-global        
    - test:
        context: org-global
    - publish:
        context: org-global    
        requires:
        - build
        - code-analysis
        - test
    - hold-deploy-qa:
        type: approval
        requires:
        - publish          
    - deploy-qa:
        context: org-global
        requires:
        - hold-deploy-qa
  stage_deploy:
    when: 
      and:
        - equal: [ stage_deploy , <<pipeline.parameters.workflow_to_execute>> ]
    jobs:
    - build:
        context: org-global
    - code-analysis:
        context: org-global        
    - test:
        context: org-global
    - publish:
        context: org-global    
        requires:
        - build
        - code-analysis
        - test 
    - hold-deploy-stage:
        type: approval
        requires:
        - publish          
    - deploy-stage:
        context: org-global
        requires:
        - hold-deploy-stage
  prod_deploy:
    when: 
      and:
        - equal: [ prod_deploy , <<pipeline.parameters.workflow_to_execute>> ]
    jobs:
    - build:
        context: org-global
        filters:
          branches:
            only: main
    - code-analysis:
        context: org-global  
        filters:
          branches:
            only: main        
    - test:
        context: org-global
        filters:
          branches:
            only: main
    - publish:
        context: org-global    
        requires:
        - build
        - code-analysis
        - test 
    - hold-deploy-prod:
        type: approval 
        requires: 
        - publish        
    - deploy-prod:
        context: org-global
        requires:
        - hold-deploy-prod
    - tag-release:
        context: org-global      
        requires:
        - deploy-prod
  dev_deploy_skiptest:
    when: 
      and:
        - equal: [ dev_deploy_skiptest , <<pipeline.parameters.workflow_to_execute>> ]
    jobs:
    - build:
        context: org-global
    - code-analysis:
        context: org-global        
    - publish:
        context: org-global    
        requires:
        - build
        - code-analysis
    - hold-deploy-dev:
        type: approval
        requires:
        - publish          
    - deploy-dev:
        context: org-global
        requires:
        - hold-deploy-dev
  qa_deploy_skiptest:
    when: 
      and:
        - equal: [ qa_deploy_skiptest , <<pipeline.parameters.workflow_to_execute>> ]
    jobs:
    - build:
        context: org-global
    - code-analysis:
        context: org-global        
    - publish:
        context: org-global    
        requires:
        - build
        - code-analysis
    - hold-deploy-qa:
        type: approval
        requires:
        - publish          
    - deploy-qa:
        context: org-global
        requires:
        - hold-deploy-qa
  stage_deploy_skiptest:
    when: 
      and:
        - equal: [ stage_deploy_skiptest , <<pipeline.parameters.workflow_to_execute>> ]
    jobs:
    - build:
        context: org-global
    - code-analysis:
        context: org-global        
    - publish:
        context: org-global    
        requires:
        - build
        - code-analysis
    - hold-deploy-stage:
        type: approval
        requires:
        - publish          
    - deploy-stage:
        context: org-global
        requires:
        - hold-deploy-stage
  prod_deploy_skiptest:
    when: 
      and:
        - equal: [ prod_deploy_skiptest , <<pipeline.parameters.workflow_to_execute>> ]
    jobs:
    - build:
        context: org-global
        filters:
          branches:
            only: main
    - code-analysis:
        context: org-global  
        filters:
          branches:
            only: main        
    - publish:
        context: org-global    
        requires:
        - build
        - code-analysis
    - hold-deploy-prod:
        type: approval 
        requires: 
        - publish        
    - deploy-prod:
        context: org-global
        requires:
        - hold-deploy-prod
    - tag-release:
        context: org-global      
        requires:
        - deploy-prod
  dev_refresh:
    when: 
      and:
         - equal: [ dev_refresh , <<pipeline.parameters.workflow_to_execute>> ]
    jobs:
    - deploy-dev:
        type: approval
        context: org-global      
  qa_refresh:
    when: 
      and:
         - equal: [ qa_refresh , <<pipeline.parameters.workflow_to_execute>> ]
    jobs:
    - deploy-qa:
        type: approval
        context: org-global
  stage_refresh:
    when: 
      and:
        - equal: [ stage_refresh , <<pipeline.parameters.workflow_to_execute>> ]
    jobs:
    - deploy-stage:
        type: approval
        context: org-global
  prod_refresh:
    when: 
      and:
        - equal: [ prod_refresh , <<pipeline.parameters.workflow_to_execute>> ]
    jobs:
    - build:
        context: org-global
        filters:
          branches:
            only: main
    - publish:
        context: org-global    
        requires:
        - build
    - hold-deploy-prod:
        type: approval 
        requires: 
        - publish        
    - deploy-prod:
        context: org-global
        requires:
        - hold-deploy-prod
    - tag-release:
        context: org-global      
        requires:
        - deploy-prod