#!/bin/bash
set -x

# This script is needed because curl won't print output on failures and return a non-zero exit status


# make webhook request with curl
JSON_POST=$1
POST_URL=$2
CURL_OUTPUT=$(curl --silent --output - --write-out "\n%{http_code}\n" -H Content-Type:application/json --data "${JSON_POST}" "${POST_URL}")

# parse output to determine return status
HTTP_STATUS="${CURL_OUTPUT##*$'\n'}"

# and set exit appropriately
if [ "${HTTP_STATUS}" == "200" ]
then
  exit 0
else
  exit 22
fi
